### PR TITLE
Address a11y and SEO concerns from Lighthouse report (and more!)

### PR DESCRIPTION
**Pull request by McCambley**
A breakdown:

SEO:
1) Our SEO was great, but the description of the page was something like `This page was created using Create React App`... not great. I updated it to something cheesy for the Search Engine gods.

Accessibility: 
1) Alt texts where there weren't any 
   - I added Alts to the `X` and `🍔` in the mobile menu. I'm not sure if they were left out intentionally. I found conflicting resources as to whether to use `alt=""` or `alt="Open menu"`. I opted for the Alts just in case, I could be wrong here.
2) Button labels where there weren't any
3) Link names where there weren't any

Extras:
1) Attached the `Messages` "Delegate Task" button to the form
3) Addressed a bug that displayed the wrong text on the "More projects..." button in the project component when switching courses while projects were being show. 
   - Recreating this bug: Go to projects, click "More projects...", switch courses, scroll down and view the button. 
   - It will display "Show less..." while only displaying the default (2) projects, even if there are more to show. When clicking "Show less..." while "less..." is already shown, no more or less projects are show, but the text will update. 
   - Now it should work as intended, as the text will reset when a new course is chosen. 

88 ➡️   98 on the accessibility score baby 🎉

_Oh yeah! The Lighthouse test is kicking a lot of warning with regards to the contrast of colors on our page. If people with impaired sight view our page, they'll have trouble viewing some of the less contrasting colors. That's on the design. We did what we were told. I didn't touch anything there._

### CODE REVIEW

**Comment by denisehung** [comment]
Hi Jake, nice improvements! I don't think I have anything to add to it. 
I'm only getting a score of 86 on Performance though... 🤔 I thought we had a higher score on that before?

**Comment by thinklikeadesigner** [comment]
> Hi Jake, nice improvements! I don't think I have anything to add to it. 
I'm only getting a score of 86 on Performance though... 🤔 I thought we had a higher score on that before? 

are you running it on development? you hhave to deploy it to get the reall score

**Review by thinklikeadesigner — APPROVED** [review]
Looks good!

**Comment by denisehung** [comment]
> > Hi Jake, nice improvements! I don't think I have anything to add to it.
> > I'm only getting a score of 86 on Performance though... 🤔 I thought we had a higher score on that before?
> 
> are you running it on development? you hhave to deploy it to get the reall score

Ohh I see! That should be the reason then

**Review by denisehung — APPROVED** [review]

**Pull request merged**
